name: wssnet_ghost3a
version: 1.0.0
description: Websocket client for node-ghost3a
dependencies:
  crypto: ^2.1.3
  encrypt: ^3.3.1
environment:
  sdk: '>=2.0.0 <3.0.0'
authors:
  - yangfanyu <yangfanyu@aliyun.com>
homepage: https://github.com/yangfanyu/node-ghost3a
